name: design
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  glassmorphism: ^3.0.0
  gradient_borders: ^1.0.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/image/
  #   - assets/svg/solid/
  #   - assets/svg/outline/
  #   - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 100