name: poscrisma
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.3
  get_it: ^7.7.0
  responsive_builder: ^0.7.1
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_dotenv: ^5.1.0
  loggy: ^2.0.3
  logger: ^2.4.0
  http: ^1.2.2
  syncfusion_flutter_charts: ^26.2.9
  signals: ^5.4.0
  mask_text_input_formatter: ^2.9.0
  sheet: ^1.0.0
  brasil_fields: ^1.15.0
  lottie: ^3.1.2
  #loginAnimation:
  flame: ^1.19.0
  flame_forge2d: ^0.18.2
  forge2d: ^0.13.1
  equatable: ^2.0.5
  #modal
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
