// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBss6AxNLV3qtA_PheGF6ZvXBZYzYN1hIQ',
    appId: '1:604903944147:web:6fd21a8c02089000738926',
    messagingSenderId: '604903944147',
    projectId: 'poscrisma-77128',
    authDomain: 'poscrisma-77128.firebaseapp.com',
    storageBucket: 'poscrisma-77128.appspot.com',
    measurementId: 'G-CDN36KDYY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhPJS7OXF3tEJHmYKynBkA8mue4neMwM8',
    appId: '1:604903944147:android:7b980585a587b918738926',
    messagingSenderId: '604903944147',
    projectId: 'poscrisma-77128',
    storageBucket: 'poscrisma-77128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ZJPZ-b9Jv4R5pm3GFNCykgqtKTT2sDY',
    appId: '1:604903944147:ios:13625d6057384b59738926',
    messagingSenderId: '604903944147',
    projectId: 'poscrisma-77128',
    storageBucket: 'poscrisma-77128.appspot.com',
    iosBundleId: 'org.poscrisma.poscrisma',
  );
}
