// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIOCACjm5V4JnxYKHZTdMTFkaOqNje72I',
    appId: '1:626405922633:web:0daf506acf58c8e3c7ac98',
    messagingSenderId: '626405922633',
    projectId: 'poscrisma-be163',
    authDomain: 'poscrisma-be163.firebaseapp.com',
    storageBucket: 'poscrisma-be163.appspot.com',
    measurementId: 'G-22MPKTN0NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpWAZnLJbGgp8jat1hO0H1fMdCfUSji44',
    appId: '1:626405922633:android:2adc355b0ce04a32c7ac98',
    messagingSenderId: '626405922633',
    projectId: 'poscrisma-be163',
    storageBucket: 'poscrisma-be163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABc5It4OariH9IbQmNi_4jC4qrbMgO-aQ',
    appId: '1:626405922633:ios:1c43b121d11fdf89c7ac98',
    messagingSenderId: '626405922633',
    projectId: 'poscrisma-be163',
    storageBucket: 'poscrisma-be163.appspot.com',
    iosBundleId: 'org.poscrisma.poscrisma',
  );
}
